### ISSUE TITLE
How do i get the requirements

### ISSUE THREAD

**Issue by Ryzora** [BrahimJarrar/Nitrx#11]
How can i get allt he requirements so Nitrx.py works?

**Comment by ClearlyNation** [comment]
Look in the main.py and install the reqs with 

```
pip install <req>
```

**Comment by Ryzora** [comment]
i don't get it
when i try to open it it closes

**Comment by Squuv** [comment]
idc lmao

**Comment by hclaim0** [comment]
You need to do it in a command prompt.
